package enum

type MediaType string

var EnumMediaType = struct {
	MediaTypeJson         MediaType
	MediaTypeProblemJson  MediaType
	MediaTypeForm         MediaType
	MediaTypeText         MediaType
	MediaTypeHtml         MediaType
	MediaTypeXml          MediaType
	MediaTypeYaml         MediaType
	MediaTypeCsv          MediaType
	MediaTypeGzip         MediaType
	MediaTypePdf          MediaType
	MediaTypeDoc          MediaType
	MediaTypeXls          MediaType
	MediaTypePpt          MediaType
	MediaTypePng          MediaType
	MediaTypeJpeg         MediaType
	MediaTypeGif          MediaType
	MediaTypeSvg          MediaType
	MediaTypeWebp         MediaType
	MediaTypeBmp          MediaType
	MediaTypeIco          MediaType
	MediaTypeTiff         MediaType
	MediaTypeAvi          MediaType
	MediaTypeMpeg         MediaType
	MediaTypeMp4          MediaType
	MediaTypeWebm         MediaType
	MediaTypeOgg          MediaType
	MediaTypeFlv          MediaType
	MediaTypeMkv          MediaType
	MediaTypeWav          MediaType
	MediaTypeMp3          MediaType
	MediaTypeOggAudio     MediaType
	MediaTypeFlac         MediaType
	MediaTypeAac          MediaType
	MediaTypeOpus         MediaType
	MediaTypeWebmAudio    MediaType
	MediaTypeMidi         MediaType
	MediaTypeJsonLd       MediaType
	MediaTypeRdf          MediaType
	MediaTypeAtom         MediaType
	MediaTypeRss          MediaType
	MediaTypeSoap         MediaType
	MediaTypeWSDL         MediaType
	MediaTypeXhtml        MediaType
	MediaTypeXforms       MediaType
	MediaTypeXslt         MediaType
	MediaTypeMathml       MediaType
	MediaTypeOebpsPackage MediaType
	MediaTypeOggContainer MediaType
	MediaTypeDavmount     MediaType
	MediaTypeXop          MediaType
	MediaTypeXenc         MediaType
}{
	MediaTypeJson:         "application/json",
	MediaTypeProblemJson:  "application/problem+json",
	MediaTypeForm:         "application/x-www-form-urlencoded",
	MediaTypeText:         "text/plain",
	MediaTypeHtml:         "text/html",
	MediaTypeXml:          "application/xml",
	MediaTypeYaml:         "application/x-yaml",
	MediaTypeCsv:          "text/csv",
	MediaTypeGzip:         "application/gzip",
	MediaTypePdf:          "application/pdf",
	MediaTypeDoc:          "application/msword",
	MediaTypeXls:          "application/vnd.ms-excel",
	MediaTypePpt:          "application/vnd.ms-powerpoint",
	MediaTypePng:          "image/png",
	MediaTypeJpeg:         "image/jpeg",
	MediaTypeGif:          "image/gif",
	MediaTypeSvg:          "image/svg+xml",
	MediaTypeWebp:         "image/webp",
	MediaTypeBmp:          "image/bmp",
	MediaTypeIco:          "image/x-icon",
	MediaTypeTiff:         "image/tiff",
	MediaTypeAvi:          "video/x-msvideo",
	MediaTypeMpeg:         "video/mpeg",
	MediaTypeMp4:          "video/mp4",
	MediaTypeWebm:         "video/webm",
	MediaTypeOgg:          "video/ogg",
	MediaTypeFlv:          "video/x-flv",
	MediaTypeMkv:          "video/x-matroska",
	MediaTypeWav:          "audio/wav",
	MediaTypeMp3:          "audio/mpeg",
	MediaTypeOggAudio:     "audio/ogg",
	MediaTypeFlac:         "audio/flac",
	MediaTypeAac:          "audio/aac",
	MediaTypeOpus:         "audio/opus",
	MediaTypeWebmAudio:    "audio/webm",
	MediaTypeMidi:         "audio/midi",
	MediaTypeJsonLd:       "application/ld+json",
	MediaTypeRdf:          "application/rdf+xml",
	MediaTypeAtom:         "application/atom+xml",
	MediaTypeRss:          "application/rss+xml",
	MediaTypeSoap:         "application/soap+xml",
	MediaTypeWSDL:         "application/wsdl+xml",
	MediaTypeXhtml:        "application/xhtml+xml",
	MediaTypeXforms:       "application/xforms+xml",
	MediaTypeXslt:         "application/xslt+xml",
	MediaTypeMathml:       "application/mathml+xml",
	MediaTypeOebpsPackage: "application/oebps-package+xml",
	MediaTypeOggContainer: "application/ogg",
	MediaTypeDavmount:     "application/davmount+xml",
	MediaTypeXop:          "application/xop+xml",
	MediaTypeXenc:         "application/xenc+xml",
}
